name: ollamacode

on:
  issue_comment:
    types: [created]

jobs:
  ollamacode:
    if: startsWith(github.event.comment.body, 'hey ollamacode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run ollamacode
        uses: 88plug/ollamacode/sdks/github@github-v1
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          model: anthropic/claude-sonnet-4-20250514
